Repository elsafluss/fitlit-starter-kit, pull requests merged in 2020-12, with the labels that each got.

#41 Feature/user info dashboard
  src/index.html
  src/scripts.js
  src/user.js
  src/userRepo.js
Labels: dashboard, iteration 1

#44 Make user info display on dashboard and user and userRepo tests pass.
  src/scripts.js
  src/user.js
  src/userRepo.js
  test/user-test.js
  test/userRepo-test.js
Labels: bug, dashboard, data structure, iteration 1, test

#45 Fix/user class
  .vscode/settings.json
  assets/admin.svg
  assets/calendar.svg
  assets/minutes.svg
  assets/person.svg
  assets/sleep.svg
  assets/water.svg
  src/scripts.js
  src/user.js
  src/userRepo.js
  test/user-test.js
  test/userRepo-test.js
Labels: bug, iteration 1

#46 Add methods to dry up hydration class
  src/userHydration.js
  test/userHydration-test.js
Labels: data structure, iteration 2

#47 Add hydration data to dashboard
  src/index.html
  src/scripts.js
  src/styles.css
Labels: dashboard, iteration 2

#48 Feature/admin selectors
  src/index.html
  src/scripts.js
  src/user.js
  src/userRepo.js
Labels: dashboard, iteration 2

#49 Feature/user sleep
  src/scripts.js
  src/userSleep.js
  test/userHydration-test.js
  test/userSleep-test.js
Labels: data structure, iteration 3, test

#50 Display user sleep data on dashboard.
  src/index.html
  src/scripts.js
  src/userHydration.js
  src/userSleep.js
  test/userSleep-test.js
Labels: dashboard, iteration 3

#51 Feature/activity class
  src/scripts.js
  src/userActivity.js
  test/userActivity-test.js
Labels: data structure, iteration 4

#52 Feature/add activity dashboard
  src/index.html
  src/scripts.js
  src/styles.css
  src/userActivity.js
  src/userSleep.js
  test/userActivity-test.js
Labels: dashboard, iteration 4

#56 Fix/refactor hydration
  src/index.html
  src/scripts.js
  src/styles.css
  src/user.js
  src/userActivity.js
  src/userHydration.js
  src/userRepo.js
  src/userSleep.js
Labels: data structure

#59 Fix/test files
  package-lock.json
  package.json
  src/index.html
  src/moment.js
  src/scripts.js
  src/styles.css
  src/user.js
  src/userActivity.js
  src/userHydration.js
  src/userRepo.js
  test/user-test.js
  test/userHydration-test.js
  test/userRepo-test.js
  test/userSleep-test.js
Labels: bug, data structure, iteration 3

#60 Fix/test files 2
  src/userActivity.js
  src/userHydration.js
  test/userActivity-test.js
  test/userHydration-test.js
Labels: data structure, test

#61 Fix/refactor scripts
  src/index.html
  src/scripts.js
  src/styles.css
  src/user.js
  src/userRepo.js
Labels: dashboard

#62 Fix/html css cleanup
  src/index.html
  src/scripts.js
  src/styles.css
  src/user.js
  src/userRepo.js
Labels: dashboard

#63 Feature add charts
  package-lock.json
  package.json
  src/chart.js
  src/index.html
  src/scripts.js
Labels: dashboard, enhancement

#65 Fix font sizes
  src/admin.js
  src/chart.js
  src/index.html
  src/moment.js
  src/scripts.js
  src/styles.css
  src/user.js
  src/userActivity.js
  src/userHydration.js
  src/userRepo.js
  src/userSleep.js
  test/admin-test.js
  test/test-data.js
  test/user-test.js
  test/userActivity-test.js
  test/userHydration-test.js
  test/userRepo-test.js
  test/userSleep-test.js
Labels: dashboard, data structure

#66 Fix activity chart that kept growing when window was resized.
  src/scripts.js
Labels: bug, dashboard
